### ISSUE TITLE
Dependencies issue while making a truly cross platform app

### ISSUE THREAD

**Issue by singwithaashish** [ollydixon/flutter_macos_video_player#14]
I am using flutter_meedu_videoplayer which supports playing video on all platform except for mac. and am getting this error 

`Because every version of video_player_macos depends on video_player_platform_interface ^5.1.1 and every version of video_player_dart_vlc depends on video_player_platform_interface ^6.0.1, video_player_macos is incompatible with video_player_dart_vlc.
And because flutter_meedu_videoplayer >=3.0.2 depends on video_player_dart_vlc ^0.1.3, video_player_macos is incompatible with flutter_meedu_videoplayer >=3.0.2.
So, because video_app depends on both video_player_macos ^1.0.6 and flutter_meedu_videoplayer ^3.0.2, version solving failed.
pub get failed (1; So, because video_app depends on both video_player_macos ^1.0.6 and flutter_meedu_videoplayer ^3.0.2, version solving failed.)`

i think updating the `video_player_platform_interface` to `^6.0.1` should solve it.

**Comment by ollydixon** [comment]
Merged :-)

**Comment by singwithaashish** [comment]
thank you very much.
